-- ==============================================================================
-- SRI GOVINDA FOOD PRODUCTS - SUPABASE DATABASE SCHEMA & REALTIME SETUP
-- Project: Sri Govinda Sales App & Inventory Realtime Hub
-- ==============================================================================

-- 1. DROP EXISTING TABLES (Safe Re-run)
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS sample_giveaways CASCADE;
DROP TABLE IF EXISTS inventory_inward CASCADE;
DROP TABLE IF EXISTS contract_pricing CASCADE;
DROP TABLE IF EXISTS buyers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS routes CASCADE;
DROP TABLE IF EXISTS reps CASCADE;

-- ------------------------------------------------------------------------------
-- 2. TABLE DEFINITIONS
-- ------------------------------------------------------------------------------

-- Delivery Beats / Routes
CREATE TABLE routes (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  short TEXT,
  hub TEXT,
  cutoff TEXT DEFAULT '4:30 PM',
  vehicle TEXT DEFAULT 'Tata Ace (1.5T Van)',
  "isSystem" BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Store / Buyer Directory & Credit Ledgers
CREATE TABLE buyers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  tier TEXT NOT NULL DEFAULT 'Retail', -- 'HoReCa', 'Wholesale', 'Retail', 'Caterer'
  phone TEXT,
  "homeRoute" TEXT,
  "creditLimit" NUMERIC DEFAULT 0,
  "pendingUdhaar" NUMERIC DEFAULT 0,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Product Catalog Master
CREATE TABLE products (
  id TEXT PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT,
  "unitSize" TEXT,
  "baseRate" NUMERIC NOT NULL DEFAULT 0,
  "initialStock" NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Custom Contract Rates (Negotiated Client Overrides)
CREATE TABLE contract_pricing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buyerId" TEXT NOT NULL,
  "productId" TEXT NOT NULL,
  "overrideRate" NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE ("buyerId", "productId")
);

-- Commercial Sales Orders
CREATE TABLE orders (
  id TEXT PRIMARY KEY,
  "repId" TEXT,
  "repName" TEXT,
  "buyerId" TEXT,
  "buyerName" TEXT,
  "buyerPhone" TEXT,
  "buyerTier" TEXT,
  "buyerHomeRoute" TEXT,
  "dispatchRoute" TEXT,
  date TEXT,
  time TEXT,
  items JSONB DEFAULT '[]'::jsonb,
  "totalUnits" NUMERIC DEFAULT 0,
  "itemsSubtotal" NUMERIC DEFAULT 0,
  "logisticsFee" NUMERIC DEFAULT 0,
  "extraRebate" NUMERIC DEFAULT 0,
  "netPayable" NUMERIC DEFAULT 0,
  "paymentMode" TEXT DEFAULT 'Cash',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Production Inward Stock Register
CREATE TABLE inventory_inward (
  id TEXT PRIMARY KEY,
  date TEXT,
  product_sku TEXT,
  product_name TEXT,
  unit_size TEXT,
  quantity_units NUMERIC DEFAULT 0,
  batch_number TEXT,
  supplier_or_source TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Free Samples & Tasting Giveaway Tracker
CREATE TABLE sample_giveaways (
  id TEXT PRIMARY KEY,
  date TEXT,
  product_sku TEXT,
  product_name TEXT,
  unit_size TEXT,
  quantity_units NUMERIC DEFAULT 0,
  store_name TEXT,
  rep_name TEXT,
  sample_reason TEXT,
  feedback_status TEXT DEFAULT 'Pending Follow-up',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Field Sales Representatives
CREATE TABLE reps (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  "defaultBase" TEXT,
  target NUMERIC DEFAULT 50000,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------------------------
-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------------------------------------------
-- Enable RLS on all tables
ALTER TABLE routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE buyers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE contract_pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_inward ENABLE ROW LEVEL SECURITY;
ALTER TABLE sample_giveaways ENABLE ROW LEVEL SECURITY;
ALTER TABLE reps ENABLE ROW LEVEL SECURITY;

-- Allow unrestricted read & write for anon and authenticated clients
CREATE POLICY "Public full access routes" ON routes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public full access buyers" ON buyers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public full access products" ON products FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public full access contract_pricing" ON contract_pricing FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public full access orders" ON orders FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public full access inventory_inward" ON inventory_inward FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public full access sample_giveaways" ON sample_giveaways FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public full access reps" ON reps FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ------------------------------------------------------------------------------
-- 4. REALTIME REPLICATION (For Instant Push to Manager Cockpit)
-- ------------------------------------------------------------------------------
-- Add all operational tables to the Supabase Realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE orders, inventory_inward, sample_giveaways, routes, buyers, products, contract_pricing, reps;

-- ------------------------------------------------------------------------------
-- 5. INITIAL SEED DATA FOR SRI GOVINDA
-- ------------------------------------------------------------------------------

-- Seed Delivery Beats
INSERT INTO routes (id, name, short, hub, cutoff, vehicle, "isSystem") VALUES
  ('all', 'All Routes / Unfiltered', 'All Stores', 'Central Depot', '4:30 PM', NULL, true),
  ('Route 1: Central Commercial / MG Road', 'Route 1: Central Commercial / MG Road', 'R1: Central', 'MG Road Central Hub', '5:00 PM', 'Tata Ace (1.5T Van)', false),
  ('Route 2: West Wholesale / Rajajinagar', 'Route 2: West Wholesale / Rajajinagar', 'R2: West Wholesale', 'Yeshwanthpur Wholesale Hub', '4:00 PM', '3-Wheeler Loader', false),
  ('Route 3: South Tech Hub / Koramangala', 'Route 3: South Tech Hub / Koramangala', 'R3: South Tech', 'Koramangala Logistics Bay', '3:30 PM', 'Tata Ace (1.5T Van)', false),
  ('Route 4: North HoReCa / Hebbal', 'Route 4: North HoReCa / Hebbal', 'R4: North HoReCa', 'Hebbal Distribution Point', '2:30 PM', 'E-Cargo Bike Fleet', false)
ON CONFLICT (id) DO NOTHING;

-- Seed Sales Representatives
INSERT INTO reps (id, name, phone, "defaultBase", target) VALUES
  ('rep_1', 'Ramesh Kumar', '9820123456', 'Route 1: Central Commercial / MG Road', 50000),
  ('rep_2', 'Suresh Verma', '9830234567', 'Route 2: West Wholesale / Rajajinagar', 75000),
  ('rep_3', 'Priya Sharma', '9840345678', 'Route 3: South Tech Hub / Koramangala', 60000)
ON CONFLICT (id) DO NOTHING;

-- Seed Product Catalog
INSERT INTO products (id, sku, name, category, "unitSize", "baseRate", "initialStock") VALUES
  ('p_1', 'GM-500', 'Royal Garam Masala', 'Blended Masalas', '500g pouch', 210, 120),
  ('p_2', 'GM-1K', 'Royal Garam Masala (Foodservice)', 'Blended Masalas', '1kg pack', 395, 80),
  ('p_3', 'CM-1K', 'Deggi Mirch Kashmiri Powder', 'Pure Spices', '1kg bag', 460, 95),
  ('p_4', 'DH-1K', 'Coriander Seed Powder (Special)', 'Pure Spices', '1kg bag', 240, 150),
  ('p_5', 'HL-1K', 'Salem Pure Turmeric Powder', 'Pure Spices', '1kg bag', 280, 140),
  ('p_6', 'BR-1K', 'Royal Dum Biryani Masala', 'Blended Masalas', '1kg pack', 490, 60),
  ('p_7', 'CL-500', 'Bold Green Cardamom (8mm)', 'Whole Spices', '500g jar', 1450, 40),
  ('p_8', 'CH-25K', 'Commercial Basmati Rice (XXL)', 'Commercial Grains', '25kg bag', 2850, 50)
ON CONFLICT (id) DO NOTHING;

-- Seed Buyers / Stores
INSERT INTO buyers (id, name, tier, phone, "homeRoute", "creditLimit", "pendingUdhaar", address) VALUES
  ('b_1', 'Hotel Grand Royal & Suites', 'HoReCa', '9845012345', 'Route 1: Central Commercial / MG Road', 75000, 18500, 'Residency Rd, Central'),
  ('b_2', 'Balaji Wholesale Mart', 'Wholesale', '9845023456', 'Route 2: West Wholesale / Rajajinagar', 150000, 42000, 'Industrial Area, Rajajinagar'),
  ('b_3', 'Laxmi Super Kirana Store', 'Retail', '9845034567', 'Route 1: Central Commercial / MG Road', 30000, 4500, 'Commercial St, Central'),
  ('b_4', 'Maharaja Caterers & Banquets', 'Caterer', '9845045678', 'Route 3: South Tech Hub / Koramangala', 60000, 0, '5th Block, Koramangala'),
  ('b_5', 'Annapurna Tiffin & Canteen', 'HoReCa', '9845056789', 'Route 1: Central Commercial / MG Road', 25000, 9200, 'Brigade Rd, Central'),
  ('b_6', 'Sri Ganesh Provision Stores', 'Retail', '9845067890', 'Route 2: West Wholesale / Rajajinagar', 40000, 11200, '1st Block, Rajajinagar')
ON CONFLICT (id) DO NOTHING;

-- Seed Negotiated Contract Pricing
INSERT INTO contract_pricing ("buyerId", "productId", "overrideRate") VALUES
  ('b_1', 'p_2', 360),
  ('b_1', 'p_6', 440),
  ('b_2', 'p_3', 410)
ON CONFLICT ("buyerId", "productId") DO NOTHING;

-- Seed Inward Stock Entry
INSERT INTO inventory_inward (id, date, product_sku, product_name, unit_size, quantity_units, batch_number, supplier_or_source) VALUES
  ('inw_1', '2026-09-18', 'GM-500', 'Royal Garam Masala', '500g pouch', 50, 'LOT-918A', 'In-House Grinding Plant'),
  ('inw_2', '2026-09-18', 'CM-1K', 'Deggi Mirch Kashmiri Powder', '1kg bag', 30, 'LOT-918B', 'APMC Yard Supplier')
ON CONFLICT (id) DO NOTHING;

-- Seed Sample Giveaway
INSERT INTO sample_giveaways (id, date, product_sku, product_name, unit_size, quantity_units, store_name, rep_name, sample_reason, feedback_status) VALUES
  ('smp_1', '2026-09-18', 'GM-1K', 'Royal Garam Masala (Foodservice)', '1kg pack', 1, 'Hotel Grand Royal & Suites', 'Ramesh Kumar', 'Chef Tasting & Menu Trial', 'Converted to Paid Client')
ON CONFLICT (id) DO NOTHING;

